export const ErrorCode = {
  // (500)
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // (404)
  NOT_FOUND: "NOT_FOUND",

  // (429)
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // (401/403)
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CREDENTIAL_EXPIRED: "CREDENTIAL_EXPIRED",
  INVALID_EXPIRY_DATE: "INVALID_EXPIRY_DATE",
  TOKEN_INVALID: "TOKEN_INVALID",
  FORBIDDEN: "FORBIDDEN",

  // (404/409)
  USER_NOT_FOUND: "USER_NOT_FOUND",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  DUPLICATE_USERNAME: "DUPLICATE_USERNAME",

  // (400)
  VALIDATION_FAILED: "VALIDATION_FAILED",
  MISSING_FIELD: "MISSING_FIELD",

  // (404/409)
  BOARD_NOT_FOUND: "BOARD_NOT_FOUND",
  BOARD_ACCESS_DENIED: "BOARD_ACCESS_DENIED",

  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  GROUP_ACCESS_DENIED: "GROUP_ACCESS_DENIED",
  USER_NOT_GROUP_MEMBER: "USER_NOT_GROUP_MEMBER",
  CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER",

  COLUMN_NOT_FOUND: "COLUMN_NOT_FOUND",
  COLUMN_ACCESS_DENIED: "COLUMN_ACCESS_DENIED",

  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_ACCESS_DENIED: "TASK_ACCESS_DENIED",

  LABEL_NOT_FOUND: "LABEL_NOT_FOUND",
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
  NOT_COMMENT_AUTHOR: "NOT_COMMENT_AUTHOR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
