export const ErrorCode = {
  // (500)
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // (401/403)
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CREDENTIAL_EXPIRED: "CREDENTIAL_EXPIRED",
  INVALID_EXPIRY_DATE: "INVALID_EXPIRY_DATE",
  TOKEN_INVALID: "TOKEN_INVALID",
  FORBIDDEN: "FORBIDDEN",

  // (404/409)
  USER_NOT_FOUND: "USER_NOT_FOUND",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  DUPLICATE_USERNAME: "DUPLICATE_USERNAME",

  // (400)
  VALIDATION_FAILED: "VALIDATION_FAILED",
  MISSING_FIELD: "MISSING_FIELD",

  // (404/409)
  BOARD_NOT_FOUND: "BOARD_NOT_FOUND",
  BOARD_ACCESS_DENIED: "BOARD_ACCESS_DENIED",

  COLUMN_NOT_FOUND: "COLUMN_NOT_FOUND",

  TASK_NOT_FOUND: "TASK_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
